### ISSUE TITLE
DelvEdit crashes upon level load

### ISSUE THREAD

**Issue by PythooonUser** [Interrupt/Boarding-Party#1]
## Summary
- I run DelvEdit, works fine
- I try to open a DAT or BIN level, DelvEdit crashes with the following traceback:
```
PS C:\Program Files (x86)\Steam\steamapps\common\Delver> java -jar .\DelvEdit.jar
SteamApi: Starting Steam API
Setting breakpad minidump AppID = 249630
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198030300570 [API loaded no]
DelverLifeCycle: Initializing Renderer
DelverLifeCycle:  Textures
DelverLifeCycle:  Shaders
DelverLifeCycle:  Lights
DelverGameScreen: LibGdx Resize
DelverLifeCycle: Resized!
DelverGameScreen: LibGdx Resize
DelverLifeCycle: Resized!
Exception in thread "LWJGL Application" java.lang.NullPointerException
        at com.interrupt.dungeoneer.gfx.Tesselator.Tesselate(Tesselator.java:259)
        at com.interrupt.dungeoneer.editor.EditorFrame.Tesselate(EditorFrame.java:2809)
        at com.interrupt.dungeoneer.editor.EditorFrame.draw(EditorFrame.java:517)
        at com.interrupt.dungeoneer.editor.EditorFrame.render(EditorFrame.java:464)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:223)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:124)
PS C:\Program Files (x86)\Steam\steamapps\common\Delver>
```
- I extract the levels from delver.jar, opening in DelvEdit works
- Copying DelvEdit to another location does not change the behaviour

Is there something bad on my end?

**Comment by Interrupt** [comment]
Is that crash with any level, or just specific ones?

**Comment by PythooonUser** [comment]
Thanks for the reply. I got it working now.
## Steps
I copied the repo into /Steam//Delver/Mods/ and executed the DelvEdit there. Using a DelvEdit copie inside the repo outside of the Steam folder did not work (sometimes it crashes, sometimes it doesn't do anything).

I created my own mod that adds a new floor (also usign a DelvEdit copie) and it worked all fine.
